---
- name: Create StackStorm system user.
  user:
    name: '{{ st2_sys_user }}'
    home: '/home/{{ st2_sys_user }}'
    generate_ssh_key: 'yes'
    ssh_key_comment: 'ansible-generated on {{ st2_sys_user }}'
    ssh_key_type: 'rsa'
    ssh_key_bits: '1024'
    ssh_key_file: '/home/{{ st2_sys_user }}/.ssh/{{ st2_sys_user }}_rsa'
  register: result

- name: Configuring StackStorm user public key-based SSH access.
  become: 'yes'
  become_user: '{{ st2_sys_user }}'
  authorized_key:
    user: '{{ st2_sys_user }}'
    key: "{{ result.ssh_public_key }}"

- name: Add StackStorm system user to sudo passwordless.
  template:
    src: 'st2.j2'
    dest: '/etc/sudoers.d/st2'
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Disable sudoers requiretty.
  replace:
    dest: '/etc/sudoers'
    regexp: '^Defaults\s+\+?requiretty'
    replace: '# Defaults requiretty'

- name: StackStorm server configuration.
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ st2_conf_scripts }}'
  register: st2_conf

- name: Configure authentication.
  htpasswd:
    path: '/etc/st2/htpasswd'
    name: '{{ st2_auth_user }}'
    password: '{{ st2_auth_pass }}'

- name: Check Mistral DB tables setup
  stat:
    path: '/etc/mistral/mistral-db-manage.upgrade.head.ansible.has.run'
  register: check_mistral_tables_setup

- name: Setup mistral DB tables.
  shell: '/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf upgrade head && touch /etc/mistral/mistral-db-manage.upgrade.head.ansible.has.run'
  when: not check_mistral_tables_setup.stat.exists | bool

- name: Check Mistral register actions
  stat:
    path: '/etc/mistral/mistral-db-manage.populate.ansible.has.run'
  register: check_mistral_register_actions

- name: Register mistral actions.
  shell: '/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf populate && touch /etc/mistral/mistral-db-manage.populate.ansible.has.run'
  when: not check_mistral_register_actions.stat.exists | bool

- name: StackStorm systemd service configuration.
  template:
    src: '{{ item }}.j2'
    dest: '/lib/systemd/system/{{ item }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'st2stream.socket'
    - 'st2stream.service'
    - 'st2auth.socket'
    - 'st2auth.service'
    - 'st2api.socket'
    - 'st2api.service'
    - 'mistral-api.service'

- name: CLI configuration environment variable.
  lineinfile:
    dest: '/etc/profile'
    state: 'present'
    line: '{{ item }}'
  loop:
    - 'export ST2_API_URL=http://{{ ansible_default_ipv4.address }}:{{ st2_port.api }}'
    - 'export ST2_AUTH_URL=http://{{ ansible_default_ipv4.address }}:{{ st2_port.auth }}'
    - 'export ST2_STREAM_URL=http://{{ ansible_default_ipv4.address }}:{{ st2_port.stream }}/v1'
