---
- name: Make StackStorm encryption keys directory.
  become: yes
  file:
    path: '/etc/st2/keys'
    state: 'directory'
    mode: '0750'
    owner: 'root'
    group: 'st2'

- name: Generate StackStorm crypto key.
  become: yes
  command: 'st2-generate-symmetric-crypto-key --key-path /etc/st2/keys'

- name: Set permissions on datastore encryption key.
  become: yes
  file:
    path: '/etc/st2/keys/datastore_key.json'
    mode: '0640'
    owner: 'root'
    group: 'st2'