---
- name: Sets MongoDB node variables for Cluster
  set_fact:
    st2_mongod_hosts: '{{ st2_servers }}'
  when:
    - st2_mongod_dept | bool

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status.
  include: 'selinux.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Installation the prometheus statsd exporter
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Configure the StackStorm datastore
  include: 'datastore.yml'

- name: Configuration the StackStorm.
  include: 'configureation.yml'

- name: Reload the StackStorm service
  shell: echo ''
  notify: 'Ensure StackStorm service is enabled'
  when:
    - st2_conf is changed or st2_update is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: ChatOps operations
  include: 'chatops.yml'
