---
- name: Set st2_selinux to false for default.
  set_fact:
    st2_selinux: "{{ false }}"

- name: Get getenforce binary.
  stat:
    path: '/usr/sbin/getenforce'
  register: getenforce_bin
  become: yes

- name: Collect getenforce output.
  command: getenforce
  register: sestatus
  when: 'getenforce_bin.stat.exists'
  changed_when: false
  become: yes

- name: Set st2_selinux to true if getenforce returns Enforcing or Permissive.
  set_fact:
    st2_selinux: "{{ true }}"
  when: 'getenforce_bin.stat.exists and ("Enforcing" in sestatus.stdout or "Permissive" in sestatus.stdout)'

- name: Allow StackStorm to listen on service port.
  seport:
    ports: '{{ item.value }}'
    proto: 'tcp'
    setype: 'http_port_t'
    state: 'present'
  with_dict:
    - '{{ st2_port }}'
  when:
    - st2_selinux | bool
